export default [
  {
    path: '/',
    redirect: '/home',
  },
  {
    name: '首页',
    path: '/home',
    component: './Home',
    icon: 'home',
  },
  {
    name: '登录',
    path: '/login',
    component: './User/Login',
    hideInMenu: true,
    layout: false,
    icon: 'login',
  },
  {
    name: '个人中心',
    path: '/user/profile',
    component: './User/PersonalCenter',
    hideInMenu: true,
    icon: 'user',
  },

  {
    name: '资料管理',
    path: '/resource',
    icon: 'solution',
    routes: [
      {
        name: '客户管理',
        path: '/resource/customer',
        component: './Customer',
      },
      {
        name: '客户成员管理',
        path: '/resource/customer/member/:teamId',
        component: './Customer/Member',
        hideInMenu: true,
      },
      {
        name: '客户详细',
        path: '/resource/customer/detail/:uuid',
        component: './Customer/Detail',
        hideInMenu: true,
      },
      {
        name: '代理机构',
        path: '/resource/agent',
        component: './Agent',
      },
      {
        name: '代理机构详情',
        path: '/resource/agent/detail/:uuid',
        component: './Agent/Detail',
        hideInMenu: true,
      },
      {
        name: '供应商管理',
        path: '/resource/supplier',
        component: './Supplier',
      },
      {
        name: '供应商详情',
        path: '/resource/supplier/detail/:uuid',
        component: './Supplier/Detail',
        hideInMenu: true,
      },
      {
        name: 'SKU管理',
        path: '/resource/sku',
        component: './Sku',
      },
      {
        name: '商品管理',
        path: '/resource/product-manage',
        component: './ProductManage',
      },
      {
        name: '商品类别',
        path: '/resource/product-category',
        component: './ProductCategory',
      },
    ],
  },
  {
    name: '员工管理',
    path: '/staff',
    icon: 'user',
    routes: [
      {
        name: '部门管理',
        path: '/staff/department',
        component: './Department',
      },
      {
        name: '部门管理详情',
        path: '/staff/department/:uuid',
        component: './Department/Detail',
        hideInMenu: true,
      },
      {
        name: '用户管理',
        path: '/staff/user',
        component: './User/Manager',
      },
      {
        name: '权限管理',
        path: '/staff/permission',
        component: './User/Permission',
      },
      {
        name: '给用户授权',
        path: '/staff/permission/:userId',
        component: './User/Permission/BindPermission',
        hideInMenu: true,
      },
    ],
  },
  {
    name: '仓库管理',
    path: '/storehouse',
    icon: 'container',
    routes: [
      {
        name: '仓库信息管理',
        path: '/storehouse/manage',
        component: './Storehouse/Manager',
      },
      {
        name: '仓库信息详情',
        path: '/storehouse/detail/:uuid',
        component: './Storehouse/Manager/Detail',
        hideInMenu: true,
      },
      {
        name: '库存管理',
        path: '/storehouse/inventory',
        icon: 'bar-chart',
        routes: [
          {
            name: '库存查询',
            path: '/storehouse/inventory/query',
            component: './Storehouse/InventoryQuery',
          },
          {
            name: '库存详情',
            path: '/storehouse/inventory/storehouse-product-detail/:uuid',
            component: './Storehouse/InventoryQuery/Detail',
            hideInMenu: true,
          },
          {
            name: '入库',
            path: '/storehouse/inventory/in',
            component: './Storehouse/InventoryIn',
          },
          {
            name: '入库详情',
            path: '/storehouse/inventory/inbound-detail/:uuid',
            component: './Storehouse/InventoryIn/Detail',
            hideInMenu: true,
          },
          {
            name: '入库详情信息',
            path: '/storehouse/inventory/inbound-detail-info/:uuid',
            component: './Storehouse/InventoryIn/DetailInfo',
            hideInMenu: true,
          },
          {
            name: '添加入库',
            path: '/storehouse/inventory/inbound-add',
            component: './Storehouse/InventoryIn/Add',
            hideInMenu: true,
          },
          {
            name: '出库',
            path: '/storehouse/inventory/out',
            component: './Storehouse/InventoryOut',
          },
          {
            name: '添加出库',
            path: '/storehouse/inventory/outbound-add',
            component: './Storehouse/InventoryOut/Add',
            hideInMenu: true,
          },
          {
            name: '出库详情',
            path: '/storehouse/inventory/outbound-detail/:uuid',
            component: './Storehouse/InventoryOut/Detail',
            hideInMenu: true,
          },
          {
            name: '库存盘点',
            path: '/storehouse/inventory/check',
            component: './Storehouse/InventoryCheck',
          },
          {
            name: '添加盘点',
            path: '/storehouse/inventory/check-add',
            component: './Storehouse/InventoryCheck/Add',
            hideInMenu: true,
          },
          {
            name: '盘点明细',
            path: '/storehouse/inventory/check-detail/:uuid',
            component: './Storehouse/InventoryCheck/Detail',
            hideInMenu: true,
          },
        ],
      },
    ],
  },
  {
    name: '采购管理',
    path: '/purchase',
    icon: 'shopping',
    routes: [
      {
        name: '委托管理',
        path: '/purchase/entrust',
        component: './EntrustOrder',
      },
      {
        name: '委托详情',
        path: '/purchase/entrust/detail/:orderId',
        component: './EntrustOrder/Detail',
        hideInMenu: true,
      },
      {
        name: '合同管理',
        path: '/purchase/agreement',
        component: './Purchase/Agreement',
      },
      {
        name: '添加合同',
        path: '/purchase/agreement/add',
        component: './Purchase/Agreement/Add',
        hideInMenu: true,
      },
      {
        name: '合同详情',
        path: '/purchase/agreement/detail/:uuid',
        component: './Purchase/Agreement/Detail',
        hideInMenu: true,
      },
      {
        name: '编辑合同',
        path: '/purchase/agreement/edit/:uuid',
        component: './Purchase/Agreement/Edit',
        hideInMenu: true,
      },
      {
        name: '采购订单',
        path: '/purchase/order',
        component: './Purchase/Order',
      },
      {
        name: '创建采购订单（期货）',
        path: '/purchase/order/add-futures/:entrustOrderId',
        component: './Purchase/Order/AddFutures',
        hideInMenu: true,
      },
      {
        name: '编辑采购订单（期货）',
        path: '/purchase/order/edit-futures/:uuid',
        component: './Purchase/Order/EditFutures',
        hideInMenu: true,
      },
      {
        name: '编辑采购订单（现货）',
        path: '/purchase/order/edit-spot/:uuid',
        component: './Purchase/Order/EditSpot',
        hideInMenu: true,
      },
      {
        name: '创建采购订单（现货）',
        path: '/purchase/order/add-spot',
        component: './Purchase/Order/AddSpot',
        hideInMenu: true,
      },
      {
        name: '采购订单详情',
        path: '/purchase/order/detail/:uuid',
        component: './Purchase/Order/Detail',
        hideInMenu: true,
      },
      {
        name: '采购订单(现货)详情',
        path: '/purchase/order/detail-spot/:uuid',
        component: './Purchase/Order/DetailSpot',
        hideInMenu: true,
      },
      {
        name: '到库登记',
        path: '/purchase/arrival',
        component: './Purchase/Arrival',
      },
      {
        name: '添加到库登记',
        path: '/purchase/arrival/add',
        component: './Purchase/Arrival/Add',
        hideInMenu: true,
      },
      {
        name: '编辑到库登记',
        path: '/purchase/arrival/edit/:uuid',
        component: './Purchase/Arrival/Add',
        hideInMenu: true,
      },
      {
        name: '到库详情',
        path: '/purchase/arrival/detail/:uuid',
        component: './Purchase/Arrival/Detail',
        hideInMenu: true,
      },
      {
        name: '结算',
        path: '/purchase/settlement',
        component: './Purchase/PurchaseBill',
      },
      {
        name: '添加结算',
        path: '/purchase/settlement/add',
        component: './Purchase/PurchaseBill/Add',
        hideInMenu: true,
      },
      {
        name: '编辑结算',
        path: '/purchase/settlement/edit/:uuid',
        component: './Purchase/PurchaseBill/Add',
        hideInMenu: true,
      },
      {
        name: '结算详情',
        path: '/purchase/settlement/detail/:uuid',
        component: './Purchase/PurchaseBill/Detail',
        hideInMenu: true,
      },
    ],
  },
  {
    name: '销售管理',
    path: '/sales',
    icon: 'shop',
    routes: [
      {
        name: '合同管理',
        path: '/sales/agreement',
        component: './Sales/Agreement',
      },
      {
        name: '创建销售合同',
        path: '/sales/agreement/create/:orderNo',
        component: './Sales/Agreement/Create',
        hideInMenu: true,
      },
      {
        name: '编辑销售合同',
        path: '/sales/agreement/edit/:agreementUuid',
        component: './Sales/Agreement/Edit',
        hideInMenu: true,
      },

      {
        name: '创建定金合同',
        path: '/sales/agreement/create-deposit/:orderNo',
        component: './Sales/Agreement/Create/deposit',
        hideInMenu: true,
      },
      
      
      {
        name: '编辑定金合同',
        path: '/sales/agreement/edit-deposit/:agreementUuid',
        component: './Sales/Agreement/Edit',
        hideInMenu: true,
      },
      {
        name: '创建尾款合同',
        path: '/sales/agreement/create-final-payment/:orderNo',
        component: './Sales/Agreement/Create/final_payment',
        hideInMenu: true,
      },
      {
        name: '编辑尾款合同',
        path: '/sales/agreement/edit-final-payment/:agreementUuid',
        component: './Sales/Agreement/Edit',
        hideInMenu: true,
      },
      {
        name: '销售订单',
        path: '/sales/order',
        component: './Sales/Order',
      },
      {
        name: '订单详情',
        path: '/sales/order/detail/:uuid',
        component: './Sales/Order/Detail',
        hideInMenu: true,
      },
      {
        name: '添加订单',
        path: '/sales/order/add/:purchaseOrderId',
        component: './Sales/Order/Add',
        hideInMenu: true,
      },
      {
        name: '编辑订单',
        path: '/sales/order/edit/:uuid',
        component: './Sales/Order/Edit',
        hideInMenu: true,
      },
      {
        name: '出库登记',
        path: '/sales/outbound',
        component: './Storehouse/OutOrder',
      },
      {
        name: '添加物流信息',
        path: '/sales/outbound/add-logistics/:uuid',
        component: './LogisticsForm',
        hideInMenu: true,
      },
      {
        name: '添加出库登记',
        path: '/sales/outbound/add',
        component: './Sales/OutOfStock/Add',
        hideInMenu: true,
      },
      {
        name: '编辑出库登记',
        path: '/sales/outbound/edit/:uuid',
        component: './Sales/OutOfStock/Add',
        hideInMenu: true,
      },
      {
        name: '出库登记详情',
        path: '/sales/outbound/detail/:uuid',
        component: './Sales/OutOfStock/Detail',
        hideInMenu: true,
      },
      {
        name: '结算',
        path: '/sales/settlement',
        component: './Settlement',
      },
      {
        name: '创建结算单',
        path: '/sales/settlement/create/:orderNo',
        component: './Settlement/Create',
        hideInMenu: true,
      },
      {
        name: '编辑结算单',
        path: '/sales/settlement/edit/:uuid',
        component: './Settlement/Edit',
        hideInMenu: true,
      },
      {
        name: '发票',
        path: '/sales/bill',
        component: './Bill',
      },
      {
        name: '支付账单',
        path: '/sales/payment-bill',
        component: './PaymentBill',
      },
      {
        name: '创建定金支付账单',
        path: '/sales/payment-bill/create/:orderNo',
        component: './PaymentBill/Create/SalesDeposit',
        hideInMenu: true,
      },
      {
        name: '编辑支付账单',
        path: '/sales/payment-bill/edit/:uuid',
        component: './PaymentBill/Edit',
        hideInMenu: true,
      },
      {
        name: '创建尾款支付账单',
        path: '/sales/payment-bill/final/create/:orderNo',
        component: './PaymentBill/Create/SalesFinal',
        hideInMenu: true,
      },
      {
        name: '添加发票',
        path: '/sales/bill/add',
        component: './Bill/Add',
        hideInMenu: true,
      },
      {
        name: '编辑发票',
        path: '/sales/bill/edit/:uuid',
        component: './Bill/Add',
        hideInMenu: true,
      },
      {
        name: '详情',
        path: '/sales/bill/detail/:uuid',
        component: './Bill/Detail',
        hideInMenu: true,
      },
    ],
  },
  {
    name: '系统管理',
    path: '/system',
    icon: 'setting',
    routes: [
      {
        name: '菜单管理',
        path: '/system/menu',
        component: './Menu',
      },
      {
        name: '菜单管理（绑定api）',
        path: '/system/menu/bindapi/:menuId',
        component: './Menu/BindApi',
        hideInMenu: true,
      },
      {
        name: '结算币种',
        path: '/system/currency',
        component: './SettlementCurrency',
      },
      {
        name: '银行信息',
        path: '/system/bankinfo',
        component: './Sys/BankInfo',
      },
      {
        name: '登录日志',
        path: '/system/loginlog',
        component: './Sys/LoginLog',
      },
      {
        name: '操作日志',
        path: '/system/oplog',
        component: './Sys/OpLog',
      },
      {
        name: 'API管理',
        path: '/system/api',
        component: './Sys/Api',
      },
      {
        name: '权限管理',
        path: '/system/permission',
        component: './Sys/Permission',
      },
      {
        name: '权限管理(绑定菜单)',
        hideInMenu: true,
        path: '/system/permission/menu/:permissionId',
        component: './Sys/Permission/BindMenu',
      },
      {
        name: '用户注册协议',
        path: '/system/user-agreement',
        component: './Sys/UserAgreement',
      },
      {
        name: '隐私政策',
        path: '/system/privacy-policy',
        component: './Sys/PrivacyPolicy',
      },
      {
        name: '关于我们',
        path: '/system/about-us',
        component: './Sys/AboutUs',
      },
      {
        name: '微信用户管理',
        path: '/system/wx-user',
        component: './Sys/WxUser',
      },
    ],
  },
  {
    component: '404',
    path: '/*',
  },
];
